/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Login endpoint
         *
         *     Authenticates user with admin/admin credentials and returns a JWT token.
         *
         *     - **username**: Must be "admin"
         *     - **password**: Must be "admin"
         *
         *     Returns a JWT token valid for 30 minutes.
         */
        post: operations["login_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pokemons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pokemons
         * @description Get paginated list of all pokemons
         *
         *     Requires authentication.
         *
         *     - **offset**: Number of pokemons to skip (default: 0)
         *     - **limit**: Number of pokemons to return (default: 20, max: 100)
         *
         *     Returns a paginated list with:
         *     - count: Total number of pokemons
         *     - next: URL for next page (if any)
         *     - previous: URL for previous page (if any)
         *     - results: List of pokemon names and URLs
         */
        get: operations["get_pokemons_pokemons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pokemons/{pokemon_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pokemon Detail
         * @description Get detailed information about a specific pokemon
         *
         *     Requires authentication.
         *
         *     - **pokemon_id**: Pokemon ID (e.g., "25") or name (e.g., "pikachu")
         *
         *     Returns detailed information including:
         *     - id, name, height, weight
         *     - abilities, types, sprites
         *     - stats, moves, and more
         */
        get: operations["get_pokemon_detail_pokemons__pokemon_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint - API information
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for deployment monitoring
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Request body for login endpoint
         * @example {
         *       "password": "admin",
         *       "username": "admin"
         *     }
         */
        LoginRequest: {
            /**
             * Username
             * @description Username
             */
            username: string;
            /**
             * Password
             * @description Password
             */
            password: string;
        };
        /**
         * LoginResponse
         * @description Response body for successful login
         */
        LoginResponse: {
            /**
             * Access Token
             * @description JWT access token
             */
            access_token: string;
            /**
             * Token Type
             * @description Token type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pokemons_pokemons_get: {
        parameters: {
            query?: {
                /** @description Number of pokemons to skip */
                offset?: number;
                /** @description Number of pokemons to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pokemon_detail_pokemons__pokemon_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pokemon_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
